# Generated by Django 5.0.1 on 2024-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_fileimport_delete_fileclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='specialization',
        ),
    ]
