# Generated by Django 5.0.1 on 2024-04-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_userprofile_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='imported_at',
        ),
    ]
