# Generated by Django 5.0.1 on 2024-04-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_patient_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='project',
            name='patients',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='base.file')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='subjects',
            field=models.ManyToManyField(related_name='projects', to='base.subject'),
        ),
        migrations.AddField(
            model_name='vitals',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.subject'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
