# Generated by Django 5.0.1 on 2024-04-03 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_vitals_patient_remove_project_patients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='fileclaim',
            old_name='doctor',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='doctors',
            new_name='users',
        ),
    ]
