# Generated by Django 5.0.1 on 2024-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_user_fileclaim_userclaim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileclaim',
            old_name='userClaim',
            new_name='user',
        ),
    ]
