# Generated by Django 5.0.1 on 2024-04-12 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_userclaim_fileclaim_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
