# Generated by Django 5.0.1 on 2024-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_subject_unique_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='anonymize',
            field=models.BooleanField(default=False),
        ),
    ]
