# Generated by Django 5.0.1 on 2024-04-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_file_anonymize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
